### PR TITLE
I18n lwc rules

### PR DESCRIPTION
**Pull request by apoblock**
@gonzalocordero @Gr8Gatsby: I'd like to hear your comment on my initial take on the I18n rules.

### CODE REVIEW

**Comment by gonzalocordero** [comment]
@apoblock Hold your thought for a min here. I'd like to figure out the rollout strategy for the utility first, then we can decide the best place to enforce these rules. 

Thank you!

**Comment by apoblock** [comment]
To give more context here:
Those rules are to promote the use of `@salesforce/localizer` as a best practice for I18N in LWC, without blocking the use other methods/libraries:

- `prefer-localizer`: give warnings (not errors), and suggest to use localizer over using Intl directly
- `no-moment`: discourage use of moment (again as a warning)

Third rule (`no-aura-localization-service`) is applicable only to the platform, so may not be enabled by default for now, but no harm with keeping it available so devs can enable it explicitly in cases like base components.


Those rules should be included in the `eslint-config-lwc` as follows:
First add the:

- `i18n`: new config that only includes those i18n rules - that can be added on top of other configs by devs who need it (e.g. in base-components) or want to test it

Then, when `@salesforce/localizer` is available in the public npm repository, update the existing sets:

- `recommended`: include `prefer-localizer` and `no-moment` with a `warn` level
- `extended`: include all 3 rules with a `warn` level

_Note:_ the `@salesforce/localizer` namespace is still not final, and may change.

**Comment by apoblock** [comment]
@gonzalocordero @Gr8Gatsby @pmdartus - those rules are to supplement the rollout of @salesforce/i18n-service (a.k.a. localizerjs), which is now released to production. Please review.

**Comment by pmdartus** [comment]
This repository hosts linting rules related to LWC. The rules i18n rules you are proposing is Salesforce platform-specific concept that isn't applicable to LWC open-source. Those rules will not be added to this project.

@gonzalocordero with the rest of the UI framework team discussed where to add rules like these ones that are related to LWC usage on the Salesforce platform. We came up with the [following proposal](https://salesforce.quip.com/cxIDA7c95R21) (internal-only link).

**Pull request closed without merging**
